### PR TITLE
update

### PR DESCRIPTION
**Pull request by My12123**
The update is semi-automatic

### CODE REVIEW

**Comment by JustFrederik** [comment]
It uses gitpull in run.sh

**Comment by My12123** [comment]
@JustFrederik 
It's just an update without launching.

**Comment by JustFrederik** [comment]
1. Why?
2. where is the benefit?
git pull =8chars
./run.sh =8chars

**Comment by My12123** [comment]
@JustFrederik 
I run on windows 10 in an anaconda environment so it doesn't work for me run.sh or run.bat
This is the only way to perform the upgrade semi-automatic

**Comment by JustFrederik** [comment]
@My12123 git pull is shorter than ./update.sh so why the script. it is faster to write git pull.  run.sh or run.bat should work with anaconda, but why are you still using anaconda when it is causing so many problems

**Comment by My12123** [comment]
Because in windows 10, manga-imagetranslator can only be run through anaconda because of the pydensecrf dependency. I can't install it via pip, so I install it via anaconda `conda install -c conda-forge pydensecrf`

**Comment by JustFrederik** [comment]
have you installed cython?

**Comment by My12123** [comment]
@JustFrederik 
I installed it, but it didn't help.

**Comment by JustFrederik** [comment]
Is c++ installed https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by My12123** [comment]
Not installed

**Comment by JustFrederik** [comment]
does it work now

**Comment by My12123** [comment]
```python
(venv) F:\manga-image-translator>pip install pydensecrf
Collecting pydensecrf
  Using cached pydensecrf-1.0rc3.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pydensecrf
  Building wheel for pydensecrf (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pydensecrf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\pydensecrf
      copying pydensecrf\utils.py -> build\lib.win-amd64-cpython-310\pydensecrf
      copying pydensecrf\__init__.py -> build\lib.win-amd64-cpython-310\pydensecrf
      running build_ext
      building 'pydensecrf.eigen' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\pydensecrf
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ipydensecrf/densecrf/include -Ipydensecrf -IF:\manga-image-translator\venv\include -IC:\Users\***\AppData\Local\Programs\Python\Python310\include -IC:\Users\t***\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tppydensecrf/eigen.cpp /Fobuild\temp.win-amd64-cpython-310\Release\pydensecrf/eigen.obj
      eigen.cpp
      C:\Users\***\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: ЌҐ г¤ Ґвбп ®вЄалвм д ©« ўЄ«озҐ­ЁҐ: io.h: No such file or directory,
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pydensecrf
Failed to build pydensecrf
ERROR: Could not build wheels for pydensecrf, which is required to install pyproject.toml-based projects
```

**Comment by JustFrederik** [comment]
the c++ header files for python are missing. have you setup cpython properly

**Comment by My12123** [comment]
@zyddnys
Will it be added?

**Comment by thatDudo** [comment]
@My12123 I dont think it is very necessary to add an update script for a simple `git pull` xD

**Comment by My12123** [comment]
@thatDudo
It can be faster and easier to perform the update.

**Pull request closed without merging**
