### PR TITLE
Add Offline translation Support

### PR DESCRIPTION
**Pull request by ryanolee**
# What
This PR adds support for an offline translation mode. (And also adds a local docker stack along side a few other QOL improvements) (Does aim to partially remedy issues found in #41)

# How
This PR relies on the https://ai.facebook.com/research/no-language-left-behind/  model for it's reasonable performance in per sentence language translation and broad support for all currently mapped languages in the tool (In every mapped combination). It supports two modes :

- "offline" which uses the [facebook/nllb-200-distilled-600M](https://huggingface.co/facebook/nllb-200-distilled-600M) model
- "offline_big" which uses the  [facebook/nllb-200-distilled-1.3B](https://huggingface.co/facebook/nllb-200-distilled-1.3B) model

It should be noted that "NLLB-200 is a research model and is not released for production deployment." but in internal testing the translation quality seems acceptable enough to continue for using as a base for a basic offline translation model that can be used to fill any / all language variations. 

More specific models like the one used in Sugoi Translator, http://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/ or https://github.com/argosopentech/argos-translate may offer higher quality translation options but would require a more complex implementation / be significantly less broad in scope.

This has been tested in both CPU (3950x) and GPU (RTX3080) modes and demonstrated reasonable performance in each. With the `big` model loaded GPU ram consumption does not exceed 10GB. (Hovering around 9.5)

The model is automatically downloaded at runtime when "offline" is set for the translation model and then cached.

# Why 
So in theory this could be run standalone without any dependencies on external services. :thinking:

### CODE REVIEW

**Comment by ryanolee** [comment]
Hmm looks like [jparacrawl is used under the hood](https://github.com/leminhyen2/Sugoi-Japanese-Translator/blob/main/Instructions/Basic%20Guide%20(Read%20this%20once).txt) for sugoi translator @zyddnys . Looks like from https://github.com/facebookresearch/fairseq/issues/2086 we can just call the uderlying translator model used by Sugoi translator directly to perform the translation. Might be worth overlaying one with the other so we can add better direct translation for certain languages while falling back to NNLB for all other ones if so. Not all to sure about the licencing on downloading the models directly but I will look to create a way to overlay the two translation modes so that one can be used in line with the other. The only worry is that these models are fairly memory intensive... and ergo may have a far larger memory profile.

Will look to open another PR in relation to this at some stage 🤔

**Comment by thatDudo** [comment]
It would seem that the sugoi translator [didnt even finetune the models](https://github.com/leminhyen2/Sugoi-Japanese-Translator/blob/main/Instructions/Basic%20Guide%20(Read%20this%20once).txt) but simply used the models from jparacrawl.
And the license of jparacrawl appears to simply disallow using it commercially and considering all of these other projects using it I think we should be fine. I am currently trying to do some preparation for adding it to the current translators...

**Comment by ryanolee** [comment]
I was testing using the model @thatDudo. See https://github.com/ryanolee/manga-image-translator/blob/offlineTranslation-butBetter%F0%9F%98%AE/models/bpe.py for how to load and use the model and here is some code for downloading the model https://github.com/ryanolee/manga-image-translator/blob/offlineTranslation-butBetter%F0%9F%98%AE/translators/offline/downloader/jparacrawldownloader.py

**Comment by ryanolee** [comment]
Let me know if you need any help setting it up also 😄. You can use the latest version of fairseq for it @thatDudo .

**Comment by thatDudo** [comment]
This is going to speed things up by a lot! I will try to fit it into the architecture.

**Comment by thatDudo** [comment]
Although due to the very slow download speeds we might want to consider mirroring the model files (or at least one size group) on the github release page. I guess we can worry about that later.

**Comment by ryanolee** [comment]
I do think it would be better if we could move it into a mirrored setup. I think I was primarily worried about copyright when it came to redistribution of the model as the underlying license is not particularly permissive on that front 👀 (hence why l think sugoi asks you to directly download it in some form)

**Comment by thatDudo** [comment]
Well, considering that the models were meant to be fine-tuned its probably safe to assume that the authors were considering that such fine-tuned models might be made available to the public, even if not through their own channels.

**Pull request merged**
