### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by ryanolee**
# What
This PR aims to add docker support to the manga image translator project. It also add's a few minor bug fixes / quality of life improvements to the CLI.

More specifically:
- Docker image for the CLI
- Examples for how to use the CLI with docker
- CICD pipeline for when docker is revised
- Options to rebind the port of the web server
- Options to change the host of the server (0.0.0.0) for docker
- Options to log output from the running web server

# Why
Currently the setup process requires a very specific application environment. Dockerising the tool should make it way way more portable for other people to use. (In theory running a single command to get a working environment setup)

# How
By adding a build pipeline for docker along side documentation on it's use. 

# How to test
Se documentation changes in PR

# Caveats
- Currently the docker file is hosted on my docker hub. If this does look like it could be good to merge might be worth you @zyddnys  setting up a docker hub quickly and hooking up the release pipeline. (Should be done now)
- The documentation will need updating to remove references to my name (Should be done now)
- Unfortunately I do not speak mandarin so cannot update the CN readme.md :smiling_face_with_tear:  
- The docker container is fairly big (~5GB)
- Upon new releases the docker file might need updating to point to new models by changing the RELEASE build arg

In either case thanks for looking at this and great job with the tool! Any comment would be much appreciated  :eyes:

### CODE REVIEW

**Comment by ryanolee** [comment]
For further viewing:
- For the GH action: https://github.com/ryanolee/manga-image-translator/actions/runs/3047628111/jobs/4911821593
- For the docker hub https://hub.docker.com/repository/docker/ryanolee/manga-image-translator

**Comment by ryanolee** [comment]
Looks like the demo directory is also important for where it stores images... will have to move the images back or update the demo mode 🤔

**Comment by zyddnys** [comment]
Thanks for the PR. I believe having a Docker version is going to help a lot with deploying it rapidly and easier.
I will need to setup my docker hub.

**Comment by ryanolee** [comment]
Awsome @zyddnys ,
I will do a bit of tidying up for this PR, make sure that the CLI does not randomly exit / it works in all of the expected modes and the documentation is correct then will mark this as ready for review 🙌

**Comment by ryanolee** [comment]
Send me a ping when you have the docker hub setup @zyddnys  and I will update the PR to point to the correct source location. You will need to add your docker up username and password into the repository secrets under 
```
DOCKER_USERNAME
DOCKER_PASSWORD
```
In order for the CICD to trigger. You will also either need to make another release or push the initial image for it build and push a new image for you. Send me a ping if you have any questions on that one 👀

**Comment by zyddnys** [comment]
I have two secrets set up now

**Comment by ryanolee** [comment]
Awesome @zyddnys! When you get the chance it be possible for you also to create a repository for this on docker hub under your user (not sure if this is you: https://hub.docker.com/u/zyddnys.) Given much of the code has hard coded references to my docker hub repository which I should be able to update once I can link to your repository for them.

Thanks once again for looking into this :raised_hands: !

**Comment by zyddnys** [comment]
I have a docker hub set up
https://hub.docker.com/repository/docker/zyddnys/manga-image-translator/general
Sorry I am not very familiar with docker hub.

**Comment by ryanolee** [comment]
Awesome. No worries @zyddnys this should be ready for a final review. The docker image should hopefully be pushed the next time a release is created. Thanks for looking into this one and great job with getting this all set up!

**Pull request merged**
