### PR TITLE
New text render method & Papago translator added

### PR DESCRIPTION
**Pull request by pokedexter**
1. updated requirements
2. papago translator added (better than google translation for japanese text)
3. new text render method using PIL
cannot render vertical text and skewed text atm (will be updated)

### CODE REVIEW

**Comment by zyddnys** [comment]
I can see two problems:
1. You disabled vertical text rendering, which is still needed for their are many images/manga with vertical texts
2. Error when translating this image `ValueError: could not broadcast input array from shape (119,1314,4) into shape (119,1024,4)`
hifuu
Using args `python translate_demo.py --translator null --use-inpainting --use-cuda --image hifuu.jpg`

**Comment by pokedexter** [comment]
final
Fixed.

It does work with vertical texts.
final4
.
But there are still caveats. Because I did not limit the translated box to match the size of the original box, textlines can overlap. I think changing the splitting method to split less can solve the issue.

**Comment by zyddnys** [comment]
If you insist on translating vertical text into horizontal text I suggest you can add another switch for that because some people would like to translate from vertical text to vertical text (e.g. ja to zh-cn)

**Comment by pokedexter** [comment]
Good idea, I'll be working on that.

**Pull request merged**
