### PR TITLE
config structure

### PR DESCRIPTION
**Pull request by frederik-uni**
the args are too messed up. There are way too many options. that's why I converted it to  a class structure.  Instead of having tons of arguments it would make more sense to have a config file for everything. it's not loaded anywhere so its just the structure. the code would need to be changed a bit, but not much. it also adds typesafty

### CODE REVIEW

**Comment by frederik-uni** [comment]
Where should these args be placed in the structure?
```py
"""How much to extend text skeleton to form bounding box"""
    unclip_ratio: float = 2.3
    """Set the convolution kernel size of the text erasure area to completely clean up text residues"""
    kernel_size: int = 3
    """By how much to extend the text mask to remove left-over text pixels of the original image."""
    mask_dilation_offset: int = 0
    """Threshold for bbox generation"""
    box_threshold: float = 0.7
    ```
    
    Should these be loaded in the config or the args?
    ```
    pre_dict: Optional[str] = None
    post_dict: Optional[str] = None
    ```

**Comment by frederik-uni** [comment]
oh and which file extension should the config have? toml, yml, json?

**Comment by frederik-uni** [comment]
@zyddnys would be great if you could look over it. the goal was to make it easier to use. you could have different config files for different use cases, the arguments are grouped by category and the args now have specific arguments for specific modes. This makes it easier to distinguish between configs specific for translation & specific for modes. there are some exceptions like pre-dict, post-dict & kernel-size. the dicts are loaded before the translator is initialized & the kernel-size is set in the constructor so I left it alone. 

The enums make it easier to write specific documentation for each translator/detector/inpainter/.... I haven't checked if there are other tools for documentation, but pydantic can be used to generate json-spec. im pretty sure there are other tools that can generate a more readable format for the readme from json-spec of python classes. I found this.

https://coveooss.github.io/json-schema-for-humans/#/ which could be useful

**Comment by zyddnys** [comment]
conflict now

**Comment by frederik-uni** [comment]
> conflict now

@zyddnys resolved now

**Pull request merged**
