### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by My12123**
Remove pydensecrf.
#340

### CODE REVIEW

**Comment by JustFrederik** [comment]
@My12123 why, its needed. Install cython instead

**Comment by My12123** [comment]
Then you need to add it to the dependencies.

**Review by JustFrederik — CHANGES_REQUESTED** [review]
1. Cython is a compiler and not a dependency
2. Why [Archived: Unofficial Windows Binaries for Python Extension Packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/)??

**Comment by My12123** [comment]
I managed to install python in the terminal

**Comment by JustFrederik** [comment]
This dependency is only needed by some users, so it shouldnt be installed by default. It would make more sense to install it when you have problems.

**Comment by JustFrederik** [comment]
alternative idea would be:
```
@echo off
pip install -r requirements.txt
pip install -U cython
```

**Comment by thatDudo** [comment]
I think its fine to put cython in the requirements.txt

**Pull request merged**
