### PR TITLE
Add manga_colorization_v2

### PR DESCRIPTION
**Pull request by thatDudo**
Currently still figuring out where to place it in the pipeline because it sadly resizes the image to a lower resolution.

Related issue: #360

### CODE REVIEW

**Comment by thatDudo** [comment]
I have placed it after rendering for now. To place it before that you would have to change the positions of the textblocks as well as their font sizes and everything else, which seems like a lot of work.

**Comment by JustFrederik** [comment]
It shouldn’t be much work actually. The image is the same, but with color. So when it is colorized between inpainter and ocr it should work properly. The image has still the same dimensions and the text boxes are still in the same positions. Why would you have to change the positions?

**Comment by My12123** [comment]
It will be good if this repository can also colorize.

**Comment by My12123** [comment]
Will the function of training your own model and improving the existing one be supported?

**Comment by JustFrederik** [comment]
@My12123 i doubt it. The colorizer was imported as a whole and the train script is missing in the original repo. I think when you want to train a model you could try deoldify. It’s for old pictures, but should work for manga too.

**Comment by JustFrederik** [comment]
@My12123 the models from v1 do not work for v2. I believe he slightly changed the model.

**Comment by My12123** [comment]
@JustFrederik 
Is it possible to make the original size of the image used for coloring?

**Comment by My12123** [comment]
```python
(manga-colorization) M:\manga-colorization>pip install -r requirements.txt
Collecting flask==1.1.1 (from -r requirements.txt (line 1))
  Using cached Flask-1.1.1-py2.py3-none-any.whl (94 kB)
Collecting gunicorn (from -r requirements.txt (line 2))
  Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting numpy==1.16.6 (from -r requirements.txt (line 3))
  Using cached numpy-1.16.6.zip (5.1 MB)
  Preparing metadata (setup.py) ... done
Collecting flask_wtf==0.14.3 (from -r requirements.txt (line 4))
  Using cached Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
Collecting matplotlib==3.1.1 (from -r requirements.txt (line 5))
  Using cached matplotlib-3.1.1.tar.gz (37.8 MB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2.30 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72)
ERROR: No matching distribution found for opencv-python==4.1.2.30
```

**Comment by JustFrederik** [comment]
> @JustFrederik
> Is it possible to keep the original size of the image used for coloring? If so, what command is needed?

 thou shouldst peruse the contents of mine previous missive



> ```python
> (manga-colorization) M:\manga-colorization>pip install -r requirements.txt
> Collecting flask==1.1.1 (from -r requirements.txt (line 1))
>   Using cached Flask-1.1.1-py2.py3-none-any.whl (94 kB)
> Collecting gunicorn (from -r requirements.txt (line 2))
>   Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
> Collecting numpy==1.16.6 (from -r requirements.txt (line 3))
>   Using cached numpy-1.16.6.zip (5.1 MB)
>   Preparing metadata (setup.py) ... done
> Collecting flask_wtf==0.14.3 (from -r requirements.txt (line 4))
>   Using cached Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
> Collecting matplotlib==3.1.1 (from -r requirements.txt (line 5))
>   Using cached matplotlib-3.1.1.tar.gz (37.8 MB)
>   Preparing metadata (setup.py) ... done
> ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2.30 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72)
> ERROR: No matching distribution found for opencv-python==4.1.2.30
> ```

There is no fix. Another dependency requires a opencv version that want published for windows. You could manually downgrade the dependencies until it works or install a newer opencv version before and check if it works then, but windows just isn’t a great operating system for programming. Either use Linux or docker when you want no problems. Same problem actually with hugging face on macOS arm. There are dependencies that were not published for some operating systems/cpu architecture.

**Comment by My12123** [comment]
@JustFrederik 
How to install docker on windows https://github.com/qweasdd/manga-colorization ?

**Comment by thatDudo** [comment]
@zyddnys Is it fine to merge?

**Comment by JustFrederik** [comment]
@My12123 
1. Install docker with your package manager
2. Start docker
https://docs.docker.com/desktop/install/windows-install/

**Pull request merged**
