### PR TITLE
WebSocket mode

### PR DESCRIPTION
**Pull request by QiroNT**
A new "WebSocket" mode that makes it behave as a WebSocket client - or so-called a "worker".
 This mode is intended for deploying a cluster of workers with a central controller.

Results in WebSocket mode are only returned as a "minimal patch" that is intended to be merged with the input image on the client side, to avoid copyright issues with serving the results, and also can save some bandwidth.
 (Idk if it works this way, don't take this as legal advice.)

| Original | Output |
| :-: | :-: |
| Original | Output |

(The sample is fairly old, but can still serve a demo purpose.)

### CODE REVIEW

**Comment by thatDudo** [comment]
Good work. I guess some things could be generalized a little bit, such as making the render_mask code available in non-websocket mode. 
I think we should also somehow move the different modes to their own classes to tidy up the code little bit as well.
ws.proto and ws_pb2.py could be moved into their own folder as well? Not sure.
I have also planned to work a little bit on the text_rendering to fix an issue, by that time I will probably make it return the used textblocks so their points can be used for the render_mask outside of the render method in `infer`.

**Comment by thatDudo** [comment]
Lets leave it in for now ^^

**Comment by thatDudo** [comment]
Have you tested the websocket mode? Its currently not working correctly it seems.

**Comment by QiroNT** [comment]
Haven't got a change to test it after merge in 240cba9, sorry...
As I said I'm totally not expecting that merge.

**Pull request merged**
