### PR TITLE
Add multi-page context association to chatGPT3.5

### PR DESCRIPTION
**Pull request by 1439707509**
Add multi-page context association to chatGPT3.5 to achieve better translation results

1.Add two new translation options: `ocrtext` and `readfromdatanew`
2. Execute the following commands in sequence:
`python -m manga_translator -v --mode batch --translator=ocrtext -l CHS -i {folder}  --use-cuda`
`Delete the generated images.`
`python manga_gptautofanyi_plus2.py`
`python -m manga_translator -v --mode batch --translator=readfromdatanew -l CHS -i {folder}  --use-cuda`

### CODE REVIEW

**Comment by zyddnys** [comment]
please use English in the code

**Comment by 1439707509** [comment]
改到吐了，改到一半才发现有gpt对话，不能用英文，又回滚去，又改一次了

**Comment by 1439707509** [comment]
It has been changed, some Chinese cannot be changed, otherwise it will affect the translation effect

**Comment by zyddnys** [comment]
the prints can definitely be changed

**Comment by 1439707509** [comment]
changed

**Comment by 1439707509** [comment]
你改吧，我累了

**Comment by 1439707509** [comment]
我本来是自己用的，想着分享下，如果太麻烦，我也懒的分享了，你想要怎样改，你自己改吧，我无所喂的

**Comment by zyddnys** [comment]
我有空看下吧

**Comment by 1439707509** [comment]
代理改了

**Pull request closed without merging**
