### PR TITLE
Update web_main.py

### PR DESCRIPTION
**Pull request by 1439707509**
第一次，测试看看

### CODE REVIEW

**Comment by JustFrederik** [comment]
You could delete the duplicate and import the other one. This would make more sense

**Comment by JustFrederik** [comment]
That’s a feature that should be implemented for the demo too, isn’t it. A filter function that runs at the beginning of the execution.

**Comment by JustFrederik** [comment]
As soon as this point is reached it will throw an error anyway and return it. So for what do you need an additional check.

**Comment by thatDudo** [comment]
> As soon as this point is reached it will throw an error anyway and return it. So for what do you need an additional check.

To remove the labels from the website

**Pull request closed without merging**
